godep: Update gogo/protobuf/proto
This is required by the newer version of `cloudfoundry/noaa` in the
preceding commit. Otherwise the following build errors happen:

    # github.com/cloudfoundry/noaa/events
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/envelope.pb.go:666: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/envelope.pb.go:669: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/envelope.pb.go:774: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/envelope.pb.go:782: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:163: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:166: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:169: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:223: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:231: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:238: undefined: proto.NewRequiredNotSetError
    Godeps/_workspace/src/github.com/cloudfoundry/noaa/events/error.pb.go:238: too many errors